
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-05-14T01:15:04.579+05:30
 * Generated source version: 3.0.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "GDMS",
                      portName = "GDMSSoap",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "file:/E:/LMG/WrkspcNeON/GDMSMockUpWebService/WebContent/wsdl/GDMSWSDLFile.wsdl",
                      endpointInterface = "org.tempuri.GDMSSoap")
                      
public class GDMSSoapImpl implements GDMSSoap {

    private static final Logger LOG = Logger.getLogger(GDMSSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.GDMSSoap#deliveryCheckForGivenDate(org.tempuri.DeliveryAvailabilityCheckForDate  parameters )*
     */
    public org.tempuri.DeliveryAvailabilityCheckForDateResponse deliveryCheckForGivenDate(DeliveryAvailabilityCheckForDate parameters) { 
        LOG.info("Executing operation deliveryCheckForGivenDate");
        System.out.println(parameters);
        try {
            org.tempuri.DeliveryAvailabilityCheckForDateResponse _return = new org.tempuri.DeliveryAvailabilityCheckForDateResponse();
            org.tempuri.ResponseAttribute _returnDeliveryAvailabilityCheckForDateResult = new org.tempuri.ResponseAttribute();
            _returnDeliveryAvailabilityCheckForDateResult.setDataCaptureResponse("DataCaptureResponse-1999358280");
            _returnDeliveryAvailabilityCheckForDateResult.setDeliveryDateCheckResponse("DeliveryDateCheckResponse-965469827");
            _returnDeliveryAvailabilityCheckForDateResult.setConnectionResponse("ConnectionResponse-1071890291");
            _returnDeliveryAvailabilityCheckForDateResult.setDeliveryDate("DeliveryDate62434191");
            _returnDeliveryAvailabilityCheckForDateResult.setDeliverySlot("DeliverySlot683360321");
            _returnDeliveryAvailabilityCheckForDateResult.setErrorMessage("ErrorMessage462735286");
            _return.setDeliveryAvailabilityCheckForDateResult(_returnDeliveryAvailabilityCheckForDateResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.GDMSSoap#helloWorld(org.tempuri.HelloWorldAlias  parameters )*
     */
    public org.tempuri.HelloWorldAliasResponse helloWorld(HelloWorldAlias parameters) { 
        LOG.info("Executing operation helloWorld");
        System.out.println(parameters);
        try {
            org.tempuri.HelloWorldAliasResponse _return = new org.tempuri.HelloWorldAliasResponse();
            _return.setHelloWorldAliasResult("HelloWorldAliasResult1642532253");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.GDMSSoap#captureSchReservationData(org.tempuri.CaptureScheduleReservationDataFromORPOS  parameters )*
     */
    public org.tempuri.CaptureScheduleReservationDataFromORPOSResponse captureSchReservationData(CaptureScheduleReservationDataFromORPOS parameters) { 
        LOG.info("Executing operation captureSchReservationData");
        System.out.println(parameters);
        try {
            org.tempuri.CaptureScheduleReservationDataFromORPOSResponse _return = new org.tempuri.CaptureScheduleReservationDataFromORPOSResponse();
            org.tempuri.ResponseAttribute _returnCaptureScheduleReservationDataFromORPOSResult = new org.tempuri.ResponseAttribute();
/*            _returnCaptureScheduleReservationDataFromORPOSResult.setDataCaptureResponse("DataCaptureResponse-1526283730");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDateCheckResponse("DeliveryDateCheckResponse-1467992981");
            _returnCaptureScheduleReservationDataFromORPOSResult.setConnectionResponse("ConnectionResponse1333193628");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDate("DeliveryDate-517039829");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliverySlot("DeliverySlot863484360");
            _returnCaptureScheduleReservationDataFromORPOSResult.setErrorMessage("ErrorMessage1673277299");
            _return.setCaptureScheduleReservationDataFromORPOSResult(_returnCaptureScheduleReservationDataFromORPOSResult);*/
            
            
            if (parameters.getStrDelyDate().equalsIgnoreCase("30-Aug-2016"))
            {	          
            _returnCaptureScheduleReservationDataFromORPOSResult.setDataCaptureResponse("SUCCESS");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDateCheckResponse("AVAILABLE");
            _returnCaptureScheduleReservationDataFromORPOSResult.setConnectionResponse("SUCCESS");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDate("");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliverySlot("");
            _returnCaptureScheduleReservationDataFromORPOSResult.setErrorMessage("");
            _return.setCaptureScheduleReservationDataFromORPOSResult(_returnCaptureScheduleReservationDataFromORPOSResult);
            }
            else if (parameters.getStrDelyDate().equalsIgnoreCase("30-Sep-2016"))
            {
                _returnCaptureScheduleReservationDataFromORPOSResult.setDataCaptureResponse("SUCCESS");
                _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDateCheckResponse("NOT_AVAILABLE");
                _returnCaptureScheduleReservationDataFromORPOSResult.setConnectionResponse("SUCCESS");
                _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDate("10-OCT-2016");
                _returnCaptureScheduleReservationDataFromORPOSResult.setDeliverySlot("Morning");
                _returnCaptureScheduleReservationDataFromORPOSResult.setErrorMessage("");
                _return.setCaptureScheduleReservationDataFromORPOSResult(_returnCaptureScheduleReservationDataFromORPOSResult);            	
            }
            else
            {
            	_returnCaptureScheduleReservationDataFromORPOSResult.setDataCaptureResponse("DataCaptureResponse-1526283730");
                _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDateCheckResponse("DeliveryDateCheckResponse-1467992981");
                _returnCaptureScheduleReservationDataFromORPOSResult.setConnectionResponse("ConnectionResponse1333193628");
                _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDate("DeliveryDate-517039829");
                _returnCaptureScheduleReservationDataFromORPOSResult.setDeliverySlot("DeliverySlot863484360");
                _returnCaptureScheduleReservationDataFromORPOSResult.setErrorMessage("ErrorMessage1673277299");
                _return.setCaptureScheduleReservationDataFromORPOSResult(_returnCaptureScheduleReservationDataFromORPOSResult);            	
            }

            
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
