
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GDMSSoap", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GDMSSoap {


    /**
     * Default function to
     * 				test web service
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.HelloWorldAliasResponse
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld_Alias")
    @WebResult(name = "HelloWorld_AliasResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public HelloWorldAliasResponse helloWorld(
        @WebParam(name = "HelloWorld_Alias", targetNamespace = "http://tempuri.org/", partName = "parameters")
        HelloWorldAlias parameters);

    /**
     * 
     * 				Function to get area and date wise delivery date confirmation
     * 			
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.DeliveryAvailabilityCheckForDateResponse
     */
    @WebMethod(operationName = "DeliveryCheckForGivenDate", action = "http://tempuri.org/DeliveryAvailabilityCheckForDate")
    @WebResult(name = "DeliveryAvailabilityCheckForDateResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public DeliveryAvailabilityCheckForDateResponse deliveryCheckForGivenDate(
        @WebParam(name = "DeliveryAvailabilityCheckForDate", targetNamespace = "http://tempuri.org/", partName = "parameters")
        DeliveryAvailabilityCheckForDate parameters);

    /**
     * 
     * 				Function to capture POS data for schedule reservation
     * 			
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.CaptureScheduleReservationDataFromORPOSResponse
     */
    @WebMethod(operationName = "CaptureSchReservationData", action = "http://tempuri.org/CaptureScheduleReservationDataFromORPOS")
    @WebResult(name = "CaptureScheduleReservationDataFromORPOSResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public CaptureScheduleReservationDataFromORPOSResponse captureSchReservationData(
        @WebParam(name = "CaptureScheduleReservationDataFromORPOS", targetNamespace = "http://tempuri.org/", partName = "parameters")
        CaptureScheduleReservationDataFromORPOS parameters);

}
