
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-05-14T01:15:04.642+05:30
 * Generated source version: 3.0.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "GDMS",
                      portName = "GDMSSoap12",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "file:/E:/LMG/WrkspcNeON/GDMSMockUpWebService/WebContent/wsdl/GDMSWSDLFile.wsdl",
                      endpointInterface = "org.tempuri.GDMSSoap")
                      
public class GDMSSoap12Impl implements GDMSSoap {

    private static final Logger LOG = Logger.getLogger(GDMSSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.GDMSSoap#deliveryCheckForGivenDate(org.tempuri.DeliveryAvailabilityCheckForDate  parameters )*
     */
    public org.tempuri.DeliveryAvailabilityCheckForDateResponse deliveryCheckForGivenDate(DeliveryAvailabilityCheckForDate parameters) { 
        LOG.info("Executing operation deliveryCheckForGivenDate");
        System.out.println(parameters);
        try {
            org.tempuri.DeliveryAvailabilityCheckForDateResponse _return = new org.tempuri.DeliveryAvailabilityCheckForDateResponse();
            org.tempuri.ResponseAttribute _returnDeliveryAvailabilityCheckForDateResult = new org.tempuri.ResponseAttribute();
            _returnDeliveryAvailabilityCheckForDateResult.setDataCaptureResponse("DataCaptureResponse-1997950574");
            _returnDeliveryAvailabilityCheckForDateResult.setDeliveryDateCheckResponse("DeliveryDateCheckResponse393567988");
            _returnDeliveryAvailabilityCheckForDateResult.setConnectionResponse("ConnectionResponse83238558");
            _returnDeliveryAvailabilityCheckForDateResult.setDeliveryDate("DeliveryDate680578939");
            _returnDeliveryAvailabilityCheckForDateResult.setDeliverySlot("DeliverySlot1720500029");
            _returnDeliveryAvailabilityCheckForDateResult.setErrorMessage("ErrorMessage-1417281175");
            _return.setDeliveryAvailabilityCheckForDateResult(_returnDeliveryAvailabilityCheckForDateResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.GDMSSoap#helloWorld(org.tempuri.HelloWorldAlias  parameters )*
     */
    public org.tempuri.HelloWorldAliasResponse helloWorld(HelloWorldAlias parameters) { 
        LOG.info("Executing operation helloWorld");
        System.out.println(parameters);
        try {
            org.tempuri.HelloWorldAliasResponse _return = new org.tempuri.HelloWorldAliasResponse();
            _return.setHelloWorldAliasResult("HelloWorldAliasResult-964505695");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.GDMSSoap#captureSchReservationData(org.tempuri.CaptureScheduleReservationDataFromORPOS  parameters )*
     */
    public org.tempuri.CaptureScheduleReservationDataFromORPOSResponse captureSchReservationData(CaptureScheduleReservationDataFromORPOS parameters) { 
        LOG.info("Executing operation captureSchReservationData");
        System.out.println(parameters);
        try {
            org.tempuri.CaptureScheduleReservationDataFromORPOSResponse _return = new org.tempuri.CaptureScheduleReservationDataFromORPOSResponse();
            org.tempuri.ResponseAttribute _returnCaptureScheduleReservationDataFromORPOSResult = new org.tempuri.ResponseAttribute();
            _returnCaptureScheduleReservationDataFromORPOSResult.setDataCaptureResponse("DataCaptureResponse-1103976583");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDateCheckResponse("DeliveryDateCheckResponse1006263655");
            _returnCaptureScheduleReservationDataFromORPOSResult.setConnectionResponse("ConnectionResponse1413085126");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliveryDate("DeliveryDate1034097903");
            _returnCaptureScheduleReservationDataFromORPOSResult.setDeliverySlot("DeliverySlot1655926130");
            _returnCaptureScheduleReservationDataFromORPOSResult.setErrorMessage("ErrorMessage-162538459");
            _return.setCaptureScheduleReservationDataFromORPOSResult(_returnCaptureScheduleReservationDataFromORPOSResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
