
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * GDMS Web Service
 * 		
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GDMS", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/E:/Android/ASF/jaxws-ri-2.2.10/jaxws-ri/bin/GDMSWSDLFile.wsdl")
public class GDMS
    extends Service
{

    private final static URL GDMS_WSDL_LOCATION;
    private final static WebServiceException GDMS_EXCEPTION;
    private final static QName GDMS_QNAME = new QName("http://tempuri.org/", "GDMS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/Android/ASF/jaxws-ri-2.2.10/jaxws-ri/bin/GDMSWSDLFile.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GDMS_WSDL_LOCATION = url;
        GDMS_EXCEPTION = e;
    }

    public GDMS() {
        super(__getWsdlLocation(), GDMS_QNAME);
    }

    public GDMS(WebServiceFeature... features) {
        super(__getWsdlLocation(), GDMS_QNAME, features);
    }

    public GDMS(URL wsdlLocation) {
        super(wsdlLocation, GDMS_QNAME);
    }

    public GDMS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GDMS_QNAME, features);
    }

    public GDMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GDMS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GDMSSoap
     */
    @WebEndpoint(name = "GDMSSoap")
    public GDMSSoap getGDMSSoap() {
        return super.getPort(new QName("http://tempuri.org/", "GDMSSoap"), GDMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GDMSSoap
     */
    @WebEndpoint(name = "GDMSSoap")
    public GDMSSoap getGDMSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "GDMSSoap"), GDMSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GDMS_EXCEPTION!= null) {
            throw GDMS_EXCEPTION;
        }
        return GDMS_WSDL_LOCATION;
    }

}
