
package com.dev.gvws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "voucherDetailFault", targetNamespace = "http://dev.com/voucherdetail")
public class VoucherDetailFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VoucherDetailFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public VoucherDetailFault_Exception(String message, VoucherDetailFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public VoucherDetailFault_Exception(String message, VoucherDetailFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.dev.gvws.VoucherDetailFault
     */
    public VoucherDetailFault getFaultInfo() {
        return faultInfo;
    }

}
