
package com.dev.gvws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VoucherDetailPortType", targetNamespace = "http://dev.com/voucherdetail")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VoucherDetailPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.dev.gvws.VoucherDetailTO
     * @throws VoucherDetailFault_Exception
     */
    @WebMethod(action = "getVoucherDetail")
    @WebResult(name = "voucherDetail_TO", targetNamespace = "http://dev.com/voucherdetail", partName = "parameters")
    public VoucherDetailTO getVoucherDetail(
        @WebParam(name = "getVoucherDetail_INTO", targetNamespace = "http://dev.com/voucherdetail", partName = "parameters")
        GetVoucherDetailINTO parameters)
        throws VoucherDetailFault_Exception
    ;

}
