
package com.dev.gvws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VoucherDetailService", targetNamespace = "http://dev.com/voucherdetail", wsdlLocation = "file:/D:/ASF/jaxws-ri/bin/giftGVMax.wsdl")
public class VoucherDetailService
    extends Service
{

    private final static URL VOUCHERDETAILSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.dev.gvws.VoucherDetailService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.dev.gvws.VoucherDetailService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/ASF/jaxws-ri/bin/giftGVMax.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/ASF/jaxws-ri/bin/giftGVMax.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VOUCHERDETAILSERVICE_WSDL_LOCATION = url;
    }

    public VoucherDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoucherDetailService() {
        super(VOUCHERDETAILSERVICE_WSDL_LOCATION, new QName("http://dev.com/voucherdetail", "VoucherDetailService"));
    }

    /**
     * 
     * @return
     *     returns VoucherDetailPortType
     */
    @WebEndpoint(name = "VoucherDetailPort")
    public VoucherDetailPortType getVoucherDetailPort() {
        return super.getPort(new QName("http://dev.com/voucherdetail", "VoucherDetailPort"), VoucherDetailPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VoucherDetailPortType
     */
    @WebEndpoint(name = "VoucherDetailPort")
    public VoucherDetailPortType getVoucherDetailPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.com/voucherdetail", "VoucherDetailPort"), VoucherDetailPortType.class, features);
    }

}
